language: node_js
notifications:
  email:
    - lsimon@commoner.com
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: OEu2S6cSUs1SQdKyfJsEuQcQ5tlaSXEXwwuQ87hZaRlr1bCsBeBYWuleEWOwHFA+rqAlPtwwmOIA0dLDRDaAzl7KhqqEPwT5Q9KmUaDr4Tq362SdHkZ4PsLQnfknGBvOLLbFOnfK1onaD7qzSeMO4EyBaqesBtJbmud/KjCYfECISYKXAre0SzZX178LeIIc2b/Ln3SgBdlHkXOO8MvrZsTvPJPI11pNreQFoyfBfs+JkAH5XNWaviDWCIpjhxArfyMBDaGClJOFs9him2r2nN5TJQSkM6Vo4rXzjENAtkx79sYtaaOV4z+jDRmPDlZiFuGPDfIQjnMmqyagBlwk4W6dxZVvrs24Qf5iQ/lponuuv1jvxCodyJdEiywbZbAoGRVtkUpXsN583mTVPK24lQg+CrAMThwZwIkk29wcqNjS3U3oG02xCEkLFm5t4WLEI4/eYg3UcLrYmvG/gncg1ZMhV7CX4Rw1ayyfj5rHfIJmAsU/ZXpc4t06GJk1ED9Y6lh1L1IKETWStcU0klXONvN3nkqnv0sXSX9YZBeWy/peabkdduGdntAT6if4z3OhlILDcSWkndc92zuLbTSBio4LsA0mS4/km28jcvfqU1FufpIo65UERzWl+oaToWtq4ULWPbPhKhEOJFHVlqx3MsazZ/PPhW7M/KHqBfT1eZ8=
global:
  secure: 9KisH5B5ilpyXie3LJxYxmPK
